// <auto-generated />

using AlphaDev.Core.Data.Sql.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AlphaDev.Core.Data.Sql.Migrations.Information
{
    [DbContext(typeof(InformationContext))]
    internal class InformationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlphaDev.Core.Data.Entities.About", b =>
            {
                b.Property<bool>("Id");

                b.Property<string>("Value")
                 .IsRequired();

                b.HasKey("Id");

                b.ToTable("Abouts");
            });

            modelBuilder.Entity("AlphaDev.Core.Data.Entities.Contact", b =>
            {
                b.Property<bool>("Id");

                b.Property<string>("Value")
                 .IsRequired();

                b.HasKey("Id");

                b.ToTable("Contacts");
            });
#pragma warning restore 612, 618
        }
    }
}